### ISSUE TITLE
A box with submenus that explains the roles of the different stakeholders and their benefits

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [Superalgos/ProjectWebsite#108]
Sugested by Ron at : https://docs.google.com/document/d/1XxUvbVNBYrYN5l11UXKWCFFE36enWr4y1RY117GJo8o/edit

On https://superalgos.org/#supermind
While it is good to be descriptive, it is scientifically proven that people have ever-dwindling attention spans nowadays. So to attract more people to your project, have more pictures to represent the concepts. As the saying goes, a picture speaks a thousand words.
 
Two critical things that i would suggest 

A box with submenus that explains the roles of the different stakeholders and their benefits. Example : 

![image](https://user-images.githubusercontent.com/9479367/52408279-d9f93f00-2ad2-11e9-9989-1a9aaf66a95c.png)

Another one is your token metrics: While it is not out yet and not finalized, it would be good to reserve a space in your front page for it.

**Comment by julian-molina** [comment]
The website has evolved considerably since this piece of feedback, so I'm closing the issue until more up to date feedback is received.
