### ISSUE TITLE
In a Nutshell Section at the home page

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [Superalgos/ProjectWebsite#51]
Create a section that explains the project in one paragraph for people that scans the home page to learn what is it about in less than 30 seconds.

**Comment by julian-molina** [comment]
Please confirm if you think this is still necessary after switching the order of the slides and sections in the homepage to have EVOLUTION first.

**Comment by julian-molina** [comment]
I believe this has been addressed.
